use crate::bytecode_compiler::Upvalue;

#[derive(Eq, PartialEq, Debug, Clone)]
pub enum OpCode {
    Constant(usize),
    Nil,
    True,
    False,
    Pop,
    GetLocal(usize),
    SetLocal(usize),
    GetGlobal(usize),
    DefineGlobal(usize),
    SetGlobal(usize),
    GetUpvalue(usize),
    SetUpvalue(usize),
    GetProperty(usize),
    SetProperty(usize),
    GetSuper(usize),
    Equal,
    Greater,
    Less,
    Add,
    Subtract,
    Multiply,
    Divide,
    Not,
    Negate,
    Print,
    Jump(usize),
    JumpIfFalse(usize),
    Loop(usize),
    Call(usize),
    Invoke(usize),
    SuperInvoke(usize),
    Closure(usize, Vec<Upvalue>),
    CloseUpvalue,
    Return,
    Class(usize),
    Inherit,
    Method(usize),
}
